### ISSUE TITLE
https-front vs caddy

### ISSUE THREAD

**Issue by louis-lau** [andris9/https-front#1]
Hey Andris,

This is pretty cool, but I'm wondering if there's any advantages to it over caddy's [on demand TLS](https://caddyserver.com/docs/automatic-https#on-demand-tls) coupled with a [storage module](https://caddyserver.com/docs/json/storage/)?

**Comment by andris9** [comment]
I considered Caddy for my use case but did not manage to get it working as I needed - generating certs for any domain name without prior configuration.

**Comment by louis-lau** [comment]
Ah, fair enough. On-demand TLS in caddy obtains a certificate during the first handshake (without prior knowledge of the domain). It can allow all domains or query an endpoint to see if domains are allowed or not.

Guess it's nice to have a Node implementation.

**Comment by louis-lau** [comment]
What are you using it for? 😁

**Comment by andris9** [comment]
I didn't get further with Caddy than this line in the documentation

> Caddy uses HTTPS for all sites by default, as long as a host name is provided in the config.

I didn't want to preconfigure host names. Maybe it is possible to do the same without configuration but I didn't find how.

We are using it with email redirect links for click tracking. Customers can use their own domain name which usually helps with deliverability. All the required info for redirects is in the GET fields so the redirect server does not care about the domain name at all, as long as it points to the correct IP address.

**Comment by andris9** [comment]
And HTTPS-Front is by no means alternative for Caddy. It is for a single use case only - proxy all requests to a single pre-defined origin, no matter the domain name or protocol.

**Comment by louis-lau** [comment]
Cool! I like it when I can use my own domains with services. And in this case there's the domain reputation advantage as well.

> HTTPS-Front is by no means alternative for Caddy

Understood! Just curious as I knew caddy could do this as well. HTTPS-Front does look simpler to set up 😁.
